services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: kyc-aml-php
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: kycuser
      DB_PASS: kycpwd
      DB_NAME: kyc_app
      DB_PORT: 3306
      DB_CHARSET: "utf8mb4"
      SEED_ADMIN_EMAIL: "admin@tess.local"
      SEED_ADMIN_PASSWORD: "Admin@1234"
      JWT_SECRET: "super-secret-change-me"
      XDEBUG_MODE: debug,develop
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
      FRONTEND_ORIGIN: http://localhost:5173
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:stable
    container_name: kyc-aml-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    image: mysql:8.4
    container_name: kyc-aml-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: kycaml
      MYSQL_USER: kycuser
      MYSQL_PASSWORD: kycpwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kyc-aml-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpwd
    ports:
      - "8081:80"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: kyc-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:
